version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    tty: true
    networks:
      - telemedicina-network
    environment:
      POSTGRES_DB: telemedicina
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
  
  telemedicina:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - telemedicina-network

networks:
  lanchonete-network:
    driver: bridge