apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres  
  template:
    metadata:
      labels:
        app: postgres  
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
            protocol: TCP
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 10
        env:
        - name: POSTGRES_DB
          value: telemedicina
        - name: POSTGRES_USER
          value: username
        - name: POSTGRES_PASSWORD
          value: password

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres  # Este seletor deve corresponder à label no Deployment
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432